# Generated by Django 2.1.1 on 2018-09-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
